In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr = np.arange(1,11)
arr

In [13]:
arr = np.linspace(1,4,3)
arr

array([1. , 2.5, 4. ])

In [35]:
import random
arr = np.random.randint(1,20,10)
arr


array([ 5,  2, 13,  5,  2,  1, 19,  1,  2,  6], dtype=int32)

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [1,3,6]
])
arr.shape #it shows the number of row and coloms in our array
arr.size #it shows the number of total element in our array
arr.dtype #it tell us the type of which type of data store in our array
arr.min() #it will print the minimum value in our array
arr.max() #it will print the maximum value from our arry
arr.sum() #it will sum the all arrays elements
arr.mean #it ill print the middle element of array
arr.argmax #it will print the index of maximum value arg mean argument
arr.argmin #it will print the index of minimum value arg mean argument

<function ndarray.mean(axis=None, dtype=None, out=None, **kwargs)>

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [1,3,6]
])

np.sum(arr,axis = 0) #it print the sum off coloms 0 mean it target to colome wise summ
np.sum(arr,axis = 1) #it print the sum off rows 1 mean it target to row wise summ



array([ 6, 15, 24, 10])

array reshaping

In [58]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

indexing

In [64]:
arr =np.arange(10,25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr_slice = arr[::2]
arr_slice

array([10, 12, 14, 16, 18, 20, 22, 24])

In [92]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [95]:
#arr[0,3] zero denote the row and 3 is denoting coloms also this method is mostly used when we need a single value
arr[4:6,:]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
import numpy as np
arr = np.arange(1,31).reshape(6,5)
arr
arr[2:3,:]

array([[11, 12, 13, 14, 15]])

In [50]:

arr = np.array([

    [
    [1,2,3,4,5,6],
    [7,8,9,0,1,3],
    [2,5,1,8,3,9]
    ],

    [
    [1,2,3,4,5,6],
    [7,8,9,1,4,9],
    [2,5,1,8,3,9]
    ],
    [
    [1,2,3,4,5,6],
    [7,8,9,5,6,7],
    [2,5,1,8,3,9]
    ]

])

arr

array([[[1, 2, 3, 4, 5, 6],
        [7, 8, 9, 0, 1, 3],
        [2, 5, 1, 8, 3, 9]],

       [[1, 2, 3, 4, 5, 6],
        [7, 8, 9, 1, 4, 9],
        [2, 5, 1, 8, 3, 9]],

       [[1, 2, 3, 4, 5, 6],
        [7, 8, 9, 5, 6, 7],
        [2, 5, 1, 8, 3, 9]]])

In [ ]:
import numpy as np

arr = np.arange(1,31)
even_num = arr %2 == 0

arr = arr(even_num)
arr

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,1])

slicee = a1[0:2]

slicee *10

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,1])

np.vstack((a,b))

np.hstack((a,b)) #it horizentally stack add kar deya hai

np.column_stack((a,b)) #it vertocally stack inthe form of row kar deya hai




array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 1]])

In [96]:
c = np.arange(1,31).reshape(6,5)
np.vsplit(c,6)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]])]